let
    // 1. Configuración (Usar TOKEN generado en Atlassian)
    URL         = "Ingrese URL",
    EMAIL       = "Ingrese Mail",
    API_TOKEN   = "Ingrese API de JIRA", 
    PROJECT_KEY = "Ingrese API KEY de JIRA",

    // 2. Auth (Base64)
    AuthKey = "Basic " & Binary.ToText(Text.ToBinary(EMAIL & ":" & API_TOKEN), BinaryEncoding.Base64),

    // 3. Cuerpo de la consulta (POST)
    CuerpoJSON = Json.FromValue([
        jql = "project = " & PROJECT_KEY & " ORDER BY created DESC",
        maxResults = 100,
        fields = {"summary", "status", "priority", "assignee", "parent", "issuetype", "duedate"}
    ]),

    // 4. Llamada a la API
    Source = Json.Document(Web.Contents(URL, [
        Headers = [
            #"Authorization" = AuthKey,
            #"Content-Type"  = "application/json",
            #"Accept"        = "application/json"
        ],
        Content = CuerpoJSON
    ])),

    // 5. Navegación
    issues = Source[issues],
    #"Converted to Table" = Table.FromList(issues, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Expanded Column1" = Table.ExpandRecordColumn(#"Converted to Table", "Column1", {"key", "fields"}, {"Key", "fields"}),
    
    // 6. Expandir campos
    #"Expanded fields" = Table.ExpandRecordColumn(#"Expanded Column1", "fields", 
        {"summary", "status", "priority", "assignee", "parent", "issuetype", "duedate"}, 
        {"Title", "Status_Rec", "Priority_Rec", "Assignee_Rec", "Parent_Rec", "Type_Rec", "Due Date"}),

    // 7. Limpiar registros anidados (Nombres dentro de los registros)
    #"Final Table" = Table.TransformColumns(#"Expanded fields", {
        {"Status_Rec",   each if _ = null then null else _[name]},
        {"Priority_Rec", each if _ = null then null else _[name]},
        {"Type_Rec",     each if _ = null then null else _[name]},
        {"Assignee_Rec", each if _ = null then "Sin asignar" else _[displayName]},
        {"Parent_Rec",   each if _ = null then "Sin Padre" else try _[fields][summary] otherwise try _[key] otherwise "Sin Padre"}
    }),

    // 8. RENOMBRAR COLUMNAS AL ESPAÑOL
    #"Renamed" = Table.RenameColumns(#"Final Table", {
        {"Key",          "Clave Jira"},
        {"Title",        "Resumen"},
        {"Status_Rec",   "Estado"},
        {"Priority_Rec", "Prioridad"},
        {"Assignee_Rec", "Responsable"},
        {"Parent_Rec",   "Épica/Padre"},
        {"Type_Rec",     "Tipo de Incidencia"},
        {"Due Date",     "Fecha de Vencimiento"}
    }),

    // 9. ASIGNAR TIPOS DE DATOS
    #"Typed" = Table.TransformColumnTypes(#"Renamed", {
        {"Clave Jira",        type text},
        {"Resumen",             type text},
        {"Estado",              type text},
        {"Prioridad",           type text},
        {"Responsable",         type text},
        {"Épica/Padre",         type text},
        {"Tipo de Incidencia",  type text},
        {"Fecha de Vencimiento", type date}
    })
in
    #"Typed"
